Step 1:

Loading the Data and libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.metrics import confusion_matrix as CM
from sklearn.metrics import accuracy_score,r2_score
from sklearn.neural_network import MLPClassifier,MLPRegressor
from sklearn.model_selection import train_test_split

from keras.models import Sequential
from keras.layers import Dense

import seaborn as sns
scaler = StandardScaler()
enc = LabelEncoder()
# Ignore warnings
#import warnings
#warnings.filterwarnings('ignore')

In [2]:
df= pd.read_csv('data_refined.csv')

In [3]:
df

Unnamed: 0 diagnosis  radius_mean  texture_mean  perimeter_mean  \
0             0         M     1.097064     -2.073335        1.269934   
1             1         M     1.829821     -0.353632        1.685955   
2             2         M     1.579888      0.456187        1.566503   
3             3         M    -0.768909      0.253732       -0.592687   
4             4         M     1.750297     -1.151816        1.776573   
..          ...       ...          ...           ...             ...   
564         564         M     2.110995      0.721473        2.060786   
565         565         M     1.704854      2.085134        1.615931   
566         566         M     0.702284      2.045574        0.672676   
567         567         M     1.838341      2.336457        1.982524   
568         568         B    -1.808401      1.221792       -1.814389   

     area_mean  smoothness_mean  compactness_mean  concavity_mean  \
0     0.984375          0.11840           0.27760         0.30010   
1     1.908708          0.08474           0.07864         0.08690   
2     1.558884          0.10960           0.15990         0.19740   
3    -0.764464          0.14250           0.28390         0.24140   
4     1.826229          0.10030           0.13280         0.19800   
..         ...              ...               ...             ...   
564   2.343856          0.11100           0.11590         0.24390   
565   1.723842          0.09780           0.10340         0.14400   
566   0.577953          0.08455           0.10230         0.09251   
567   1.735218          0.11780           0.27700         0.35140   
568  -1.347789          0.05263           0.04362         0.00000   

     concave points_mean  symmetry_mean  fractal_dimension_mean  \
0                0.14710         0.2419                 0.07871   
1                0.07017         0.1812                 0.05667   
2                0.12790         0.2069                 0.05999   
3                0.10520         0.2597                 0.09744   
4                0.10430         0.1809                 0.05883   
..                   ...            ...                     ...   
564              0.13890         0.1726                 0.05623   
565              0.09791         0.1752                 0.05533   
566              0.05302         0.1590                 0.05648   
567              0.15200         0.2397                 0.07016   
568              0.00000         0.1587                 0.05884   

     diagnosis_encoded  
0                    1  
1                    1  
2                    1  
3                    1  
4                    1  
..                 ...  
564                  1  
565                  1  
566                  1  
567                  1  
568                  0  

[569 rows x 13 columns]

In [4]:
df = df.drop(df.iloc[:, 0:2], axis=1)
df

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0       1.097064     -2.073335        1.269934   0.984375          0.11840   
1       1.829821     -0.353632        1.685955   1.908708          0.08474   
2       1.579888      0.456187        1.566503   1.558884          0.10960   
3      -0.768909      0.253732       -0.592687  -0.764464          0.14250   
4       1.750297     -1.151816        1.776573   1.826229          0.10030   
..           ...           ...             ...        ...              ...   
564     2.110995      0.721473        2.060786   2.343856          0.11100   
565     1.704854      2.085134        1.615931   1.723842          0.09780   
566     0.702284      2.045574        0.672676   0.577953          0.08455   
567     1.838341      2.336457        1.982524   1.735218          0.11780   
568    -1.808401      1.221792       -1.814389  -1.347789          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  diagnosis_encoded  
0                   0.07871                  1  
1                   0.05667                  1  
2                   0.05999                  1  
3                   0.09744                  1  
4                   0.05883                  1  
..                      ...                ...  
564                 0.05623                  1  
565                 0.05533                  1  
566                 0.05648                  1  
567                 0.07016                  1  
568                 0.05884                  0  

[569 rows x 11 columns]

In [5]:
X = df.drop('diagnosis_encoded', axis = 1)
X

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0       1.097064     -2.073335        1.269934   0.984375          0.11840   
1       1.829821     -0.353632        1.685955   1.908708          0.08474   
2       1.579888      0.456187        1.566503   1.558884          0.10960   
3      -0.768909      0.253732       -0.592687  -0.764464          0.14250   
4       1.750297     -1.151816        1.776573   1.826229          0.10030   
..           ...           ...             ...        ...              ...   
564     2.110995      0.721473        2.060786   2.343856          0.11100   
565     1.704854      2.085134        1.615931   1.723842          0.09780   
566     0.702284      2.045574        0.672676   0.577953          0.08455   
567     1.838341      2.336457        1.982524   1.735218          0.11780   
568    -1.808401      1.221792       -1.814389  -1.347789          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  
0                   0.07871  
1                   0.05667  
2                   0.05999  
3                   0.09744  
4                   0.05883  
..                      ...  
564                 0.05623  
565                 0.05533  
566                 0.05648  
567                 0.07016  
568                 0.05884  

[569 rows x 10 columns]

In [6]:
y= df['diagnosis_encoded']
y

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis_encoded, Length: 569, dtype: int64

Step 2:

Train Test Split

In [7]:
train_ratio = 0.80
validation_ratio = 0.10
test_ratio = 0.10
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=1 - train_ratio)

# test is now 10% of the initial data set
# validation is now 10% of the initial data set
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, test_size=test_ratio/(test_ratio + validation_ratio)) 

print(x_train, x_val, x_test)

     radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
88     -0.501936      0.584176       -0.502069  -0.536936          0.08772   
78      1.719055      1.089149        2.130809   1.678336          0.12860   
527    -0.507616     -1.633519       -0.536668  -0.530110          0.09003   
43     -0.240643      0.230461       -0.191495  -0.311967          0.10410   
8      -0.320167      0.588830       -0.184080  -0.384207          0.12730   
..           ...           ...             ...        ...              ...   
103    -1.207427      0.025680       -1.154110  -1.014176          0.10050   
501    -0.087275      1.210157        0.014868  -0.167771          0.11620   
172     0.378508     -1.721948        0.433773   0.233247          0.12570   
284    -0.351408     -0.835335       -0.324951  -0.393308          0.07818   
3      -0.768909      0.253732       -0.592687  -0.764464          0.14250   

     compactness_mean  concavity_mean  concave points_mean  sym

Step 3.1-3.3:

Sklearn ANN Classifier

In [8]:
def SKClass():
    model = MLPClassifier(hidden_layer_sizes=(50,50,50), 
                      activation='relu', 
                      solver='adam', 
                      batch_size=20, 
                      max_iter=400, 
                      random_state=0,
                      verbose = False)    
    model.fit(x_train, y_train) 
    y1_pred = model.predict(x_test)
    y2_pred = model.predict(x_val)
    
    confusion_matrix1 = CM(y_test, y1_pred)
    confusion_matrix2 = CM(y_val, y2_pred)
    
    print('Accuracy score of test data: ' + str(accuracy_score(y_test,y1_pred)*100))
    print('Accuracy score of validation data: ' + str(accuracy_score(y_val,y2_pred)*100))
    
    
    
    return confusion_matrix1,confusion_matrix2
SKClass()

Accuracy score of test data: 94.73684210526315
Accuracy score of validation data: 87.71929824561403


(array([[38,  1],
        [ 2, 16]], dtype=int64),
 array([[29,  5],
        [ 2, 21]], dtype=int64))

In [9]:
def ANNClass():
    model = Sequential()

    model.add(Dense(units=50, activation='relu'))
    model.add(Dense(units=50, activation='relu'))
    model.add(Dense(units=50, activation='relu'))
    model.add(Dense(units=1, activation='relu'))


    model.compile(optimizer = 'adam',loss = "mean_squared_error",metrics = ['mean_squared_error'])

    model.fit(x_train, y_train, batch_size = 20, epochs = 20,verbose=False)
    y1_pred = model.predict(x_test)
    y2_pred = model.predict(x_val)

    y1_pred[np.where((y1_pred)>0.5)]=1
    y1_pred[np.where((y1_pred)<=0.5)]=0

    y2_pred[np.where((y2_pred)>0.5)]=1
    y2_pred[np.where((y2_pred)<=0.5)]=0

    confusion_matrix1 = CM(y_test, y1_pred)
    confusion_matrix2 = CM(y_val, y2_pred)

    print('Accuracy score of test data: ' + str(accuracy_score(y_test,y1_pred)*100))
    print('Accuracy score of validation data: ' + str(accuracy_score(y_val,y2_pred)*100))



    return confusion_matrix1,confusion_matrix2

ANNClass()

2/2 [==============================] - 0s 1ms/step
Accuracy score of test data: 89.47368421052632
Accuracy score of validation data: 92.98245614035088


(array([[37,  2],
        [ 4, 14]], dtype=int64),
 array([[32,  2],
        [ 2, 21]], dtype=int64))

Step 3.7:

ANN's seem to get a better score of around 2-4% higher than the best Classifiers used before, however Keras Classifiers seem to be extremely in-efficient.

Step 4:

Loading Insurance and stuff

In [10]:
ins=pd.read_csv('insurance_refined.csv')
ins

Unnamed: 0       age  sex       bmi  children  smoker  region   charges
0              0 -1.438764    0 -0.453320         0       1       3  0.298584
1              1 -1.509965    1  0.509621         1       0       2 -0.953689
2              2 -0.797954    1  0.383307         3       0       2 -0.728675
3              3 -0.441948    1 -1.305531         0       0       1  0.719843
4              4 -0.513149    1 -0.292556         0       0       1 -0.776802
...          ...       ...  ...       ...       ...     ...     ...       ...
1333        1333  0.768473    1  0.050297         3       0       1 -0.220551
1334        1334 -1.509965    0  0.206139         0       0       0 -0.914002
1335        1335 -1.509965    0  1.014878         0       0       2 -0.961596
1336        1336 -1.296362    0 -0.797813         0       0       3 -0.930362
1337        1337  1.551686    0 -0.261388         0       1       1  1.311053

[1338 rows x 8 columns]

In [11]:
ins = ins.drop(ins.iloc[:, 0:1], axis=1)
ins

age  sex       bmi  children  smoker  region   charges
0    -1.438764    0 -0.453320         0       1       3  0.298584
1    -1.509965    1  0.509621         1       0       2 -0.953689
2    -0.797954    1  0.383307         3       0       2 -0.728675
3    -0.441948    1 -1.305531         0       0       1  0.719843
4    -0.513149    1 -0.292556         0       0       1 -0.776802
...        ...  ...       ...       ...     ...     ...       ...
1333  0.768473    1  0.050297         3       0       1 -0.220551
1334 -1.509965    0  0.206139         0       0       0 -0.914002
1335 -1.509965    0  1.014878         0       0       2 -0.961596
1336 -1.296362    0 -0.797813         0       0       3 -0.930362
1337  1.551686    0 -0.261388         0       1       1  1.311053

[1338 rows x 7 columns]

In [12]:
Xins = ins.drop('charges', axis = 1)
Xins

age  sex       bmi  children  smoker  region
0    -1.438764    0 -0.453320         0       1       3
1    -1.509965    1  0.509621         1       0       2
2    -0.797954    1  0.383307         3       0       2
3    -0.441948    1 -1.305531         0       0       1
4    -0.513149    1 -0.292556         0       0       1
...        ...  ...       ...       ...     ...     ...
1333  0.768473    1  0.050297         3       0       1
1334 -1.509965    0  0.206139         0       0       0
1335 -1.509965    0  1.014878         0       0       2
1336 -1.296362    0 -0.797813         0       0       3
1337  1.551686    0 -0.261388         0       1       1

[1338 rows x 6 columns]

In [13]:
yins= ins['charges']
yins

0       0.298584
1      -0.953689
2      -0.728675
3       0.719843
4      -0.776802
          ...   
1333   -0.220551
1334   -0.914002
1335   -0.961596
1336   -0.930362
1337    1.311053
Name: charges, Length: 1338, dtype: float64

Step 5:

Good ol train-test-split

In [14]:
xins_train, xins_test, yins_train, yins_test = train_test_split(Xins, yins, test_size=1 - train_ratio)

# test is now 10% of the initial data set
# validation is now 10% of the initial data set
xins_val, xins_test, yins_val, yins_test = train_test_split(xins_test, yins_test, test_size=test_ratio/(test_ratio + validation_ratio)) 

print(xins_train, xins_val, xins_test)

           age  sex       bmi  children  smoker  region
397  -1.296362    1  0.058499         0       0       2
836  -0.228344    1  0.137240         0       0       3
92    1.409283    1 -0.136714         3       1       0
970   0.768473    0 -0.410668         3       0       2
1208 -0.157143    0 -0.838004         1       1       0
...        ...  ...       ...       ...     ...     ...
941   0.768473    0  2.530649         1       0       2
9     1.480485    0 -0.791252         0       0       1
931  -0.014740    0  0.301285         1       0       3
885  -0.513149    1 -0.284354         1       1       2
1147 -1.367563    0  0.206139         0       0       1

[1070 rows x 6 columns]            age  sex       bmi  children  smoker  region
927   1.266881    0 -1.732867         1       0       3
1240  0.910875    1  1.826898         2       1       2
74    0.341265    1 -0.535342         2       0       3
1100 -0.441948    0 -1.897732         2       1       0
458   1.195680    1  1.

Step 6.1:

Sklearn ANN Regressor

In [15]:
def InsSKReg():
    model = MLPRegressor(hidden_layer_sizes=(24,24,24), activation='relu',
                         solver='adam', batch_size=20, max_iter=70, random_state=0)
    model.fit(xins_train, yins_train) 
    y1_pred = model.predict(xins_test)
    y2_pred = model.predict(xins_val)
    
    score1 = r2_score(yins_test,y1_pred)
    score2 = r2_score(yins_val,y2_pred)
    
    return score1,score2

InsSKReg()

D:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (70) reached and the optimization hasn't converged yet.
  warnings.warn(


(0.8484458024188242, 0.8375662789968943)

Keras ANN Regressor

In [16]:
def InsKerReg():
    
    model = Sequential()
        
    model.add(Dense(units=30, activation='relu'))
    
    #Adding Hidden Layer
    model.add(Dense(units=30, activation='relu'))
    model.add(Dense(units=30, activation='relu'))
    
    #Adding Output Layer
    model.add(Dense(units=1, activation='relu'))
    
    model.compile(optimizer = 'adam', loss ='mean_squared_error', metrics = ['mean_squared_error'])
    model.fit(xins_train, yins_train, batch_size = 20, epochs = 20,verbose=False)
    y1_pred = model.predict(xins_test)
    y2_pred = model.predict(xins_val)
    
    score1 = r2_score(yins_test,y1_pred)
    score2 = r2_score(yins_val,y2_pred)
    
    return score1,score2
InsKerReg()

Epoch 1/20
54/54 [==============================] - 0s 548us/step - loss: 0.8702 - mean_squared_error: 0.8702
Epoch 2/20
54/54 [==============================] - 0s 548us/step - loss: 0.6315 - mean_squared_error: 0.6315
Epoch 3/20
54/54 [==============================] - 0s 567us/step - loss: 0.4327 - mean_squared_error: 0.4327
Epoch 4/20
54/54 [==============================] - 0s 548us/step - loss: 0.3887 - mean_squared_error: 0.3887
Epoch 5/20
54/54 [==============================] - 0s 567us/step - loss: 0.3767 - mean_squared_error: 0.3767
Epoch 6/20
54/54 [==============================] - 0s 548us/step - loss: 0.3759 - mean_squared_error: 0.3759
Epoch 7/20
54/54 [==============================] - 0s 548us/step - loss: 0.3720 - mean_squared_error: 0.3720
Epoch 8/20
54/54 [==============================] - 0s 585us/step - loss: 0.3663 - mean_squared_error: 0.3663
Epoch 9/20
54/54 [==============================] - 0s 567us/step - loss: 0.3645 - mean_squared_error: 0.3645
Epoch 10/2

(0.6690640145808142, 0.6398038432323357)

I was able to get significantly higher regression scores using Random Forests and SVRs than I did with ANNs and while I could fine tweak the ANN to get to that point, I dont see a purpose in doing so with such a small dataset